Feat skyline 524
wechat-miniprogram/weui-miniprogram pull request #232
Opened 2023-06-21 06:25 UTC by xxxBW

feat：adapt skyline

2023-06-21 06:35 UTC, seasonhuang commented on src/components/dialog/dialog.wxml
> +      <!-- <view bindtap="close" class="weui-dialog__wrp {{extClass}}"> -->
这里去掉了是无用代码吗

2023-06-21 06:35 UTC, seasonhuang commented on src/components/gallery/gallery.ts
> +            console.log('hideGallery')
去掉 log

2023-06-21 06:36 UTC, seasonhuang commented on src/components/grids/grids.ts
> +                    console.log(res)
去掉 log

2023-06-21 06:36 UTC, seasonhuang commented on src/components/half-screen-dialog/half-screen-dialog.ts
> +            console.log('1111', e)
去掉 log，下同

2023-06-21 06:38 UTC, seasonhuang commented on src/components/slideview/slideview.ts
> +            console.log('touchstart')
去掉 log

2023-06-21 06:39 UTC, seasonhuang commented on src/components/slideview/slideview.ts
> +            this.applyAnimatedStyle('.weui-slideview__left', () => {
这里跑在 webview 是否也正常

2023-06-21 06:39 UTC, seasonhuang commented on src/components/slideview/slideview.wxs
> +    console.log('--------', ins)
去掉 log，下同

2023-06-21 06:46 UTC, seasonhuang commented on src/components/tabbar/tabbar.less
> +// @media only screen and (min-width: 450px) {
这段会有会问题不？skyline 不支持，写了也没效果，如果不注释掉会跟 webview 对不齐吗

2023-06-21 06:48 UTC, seasonhuang commented on src/components/toptips/toptips.json
> +  "componentFramework": "glass-easel",
自定义组件里应该不需要配 glass-easel ，跟随页面来的

2023-06-21 07:02 UTC, seasonhuang commented on src/components/skyline-patch.wxss
> +    -webkit-box-direction: normal;
-webkit 开头的 skyline 都不支持，感觉可以不用加

2023-06-21 08:44 UTC, xxxBW commented on src/components/tabbar/tabbar.less
> +// @media only screen and (min-width: 450px) {
这里 webview 下显示有点问题

2023-07-11 08:38 UTC, xxxBW commented on mpflow.config.js
改appid

2023-07-11 08:43 UTC, seasonhuang requested changes

2023-07-11 08:43 UTC, seasonhuang commented on mpflow.config.js
> +    appId: 'wxa1ffed530ccba79d',
这个换成小程序示例的 appid 好些 @xxxBW

2023-07-18 07:51 UTC, seasonhuang commented on src/components/badge/badge.ts
> -        addGlobalClass: true
这个应该不能去掉？这样在 webview 下能兼容

2023-07-18 07:52 UTC, seasonhuang commented on src/components/actionsheet/actionsheet.wxml
> +            class="weui-actionsheet {{extClass}}"
`{{innerShow ? 'weui-animate-slide-up' : 'weui-animate-slide-down'}}` 这个去掉是预期的么

2023-07-19 10:01 UTC, seasonhuang commented on src/components/badge/badge.ts
> -        addGlobalClass: true
是改成了 styleIsolation，那 webview 也是兼容的

2023-07-26 04:51 UTC, seasonhuang commented
LGTM

2023-12-19 07:08 UTC, merged