fix: package-lock.json and style or interactive bug
wechat-miniprogram/weui-miniprogram pull request #249
Opened 2024-07-17 14:38 UTC by gaoachao

2024-07-18 06:26 UTC, Tidyzq requested changes

2024-07-18 06:26 UTC, Tidyzq commented on src/components/half-screen-dialog/half-screen-dialog.wxml
> +<view wx:if="{{wrapperShow && mask}}" class="weui-mask {{innerShow ? 'weui-animate-fade-in' : 'weui-animate-fade-out' }}" style="z-index:900" bindtap="close" data-type="close" aria-role="button" aria
这个关闭按钮从 aria-role="dialog" 中拿出来，可能导致朗读模式下无法选中，确定这里没问题么？

2024-07-18 06:26 UTC, Tidyzq commented on src/components/half-screen-dialog/half-screen-dialog.wxml
> +<view wx:if="{{wrapperShow && mask}}" class="weui-mask {{innerShow ? 'weui-animate-fade-in' : 'weui-animate-fade-out' }}" style="z-index:900" bindtap="close" data-type="close" aria-role="button" aria
另外需要跑一下 npm run test

2024-07-18 11:59 UTC, gaoachao commented on src/components/half-screen-dialog/half-screen-dialog.wxml
> +<view wx:if="{{wrapperShow && mask}}" class="weui-mask {{innerShow ? 'weui-animate-fade-in' : 'weui-animate-fade-out' }}" style="z-index:900" bindtap="close" data-type="close" aria-role="button" aria
这个应该是 mask，不过这里的  aria-role="button"  aria-label="关闭" 好像改成  aria-role="mask"  aria-label="蒙层" 更合适点

2024-07-26 06:23 UTC, gaoachao commented on src/components/half-screen-dialog/half-screen-dialog.wxml
> +<view wx:if="{{wrapperShow && mask}}" class="weui-mask {{innerShow ? 'weui-animate-fade-in' : 'weui-animate-fade-out' }}" style="z-index:900" bindtap="close" data-type="close" aria-role="button" aria
test snap 好多组件都需要改，之前那次兼容 skyline 开始就没更新 snap。看了一下工作比较大，可能可以后续抽时间搞。

2024-07-26 06:29 UTC, gaoachao commented on src/components/half-screen-dialog/half-screen-dialog.wxml
> +<view wx:if="{{wrapperShow && mask}}" class="weui-mask {{innerShow ? 'weui-animate-fade-in' : 'weui-animate-fade-out' }}" style="z-index:900" bindtap="close" data-type="close" aria-role="button" aria
https://github.com/wechat-miniprogram/weui-miniprogram/pull/249/commits/21bb444108e3c11c73ff5db64eb4135fa15f194d

2024-08-01 06:31 UTC, merged